[server]
address = "127.0.0.1"
port = 8080

[logging]
level = "debug"

[database]
# DATABASE_URL=postgres://{user}:{password}@{hostname}:{port}/{database-name}
username = "dev"
password = "dev"
netloc = "localhost"
port = 5432
database_name = "vrme_server"
