# Example config

[server]
hostname = "127.0.0.1"
port = 8080

[logging]
# Log levels:
#
# MOST VERBOSE 			TRACE
#						DEBUG
#						INFO
#						WARN
# LEAST VERBOSE			ERROR
level = "INFO"

[database]
# We use PostgreSQL (12+)
hostname = "127.0.0.1"
port = 5432
# Name of the database
database_name = "vrme_server_prod"
username = "vrme_server_user"
# WARNING: Use a more secure password!
password = "123456"

[auth]
# Length of `auth_token` in bytes
auth_token_length = 32
# Expiration time of `auth_token` in days
auth_token_validity_duration = 30
